// <auto-generated />
namespace DbBox.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class None : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(None));
        
        string IMigrationMetadata.Id
        {
            get { return "201307300135551_None"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
